spring:
  application:
    name: talkweave
  profiles:
    default: managed
  main:
    web-application-type: servlet
    banner-mode: off
logging:
  level:
    org.springframework.ai: OFF
    org.springframework.web.client: OFF
    org.springframework.web.reactive.function.client: OFF
